name: mini-crm
services:
  api:
    networks:
      - crm-network
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./:/mini-crm/
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "crmadmin"
      DB_PASS: "password"
      DB_NAME: "mini_crm_db"
      ELASTIC_HOST: "elasticsearch"
      ELASTIC_PORT: "9200"
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
  db:
    image: postgres:latest
    networks:
      - crm-network
    expose:
      - "5432"
    ports:
      - 5432:5432
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: crmadmin
      POSTGRES_DB: mini_crm_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U crmadmin -d mini_crm_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  adminer:
    image: adminer
    restart: always
    networks:
      - crm-network
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false  # Disable security for development (not recommended for production)
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - crm-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g

networks:
  crm-network:
    name: crm-network

volumes:
  elasticsearch_data:
