"""init

Revision ID: 4bfd7ffbf7cf
Revises: 
Create Date: 2024-11-12 06:36:19.651906

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bfd7ffbf7cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=True)
    op.create_table('enummodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enummodel_name'), 'enummodel', ['name'], unique=True)
    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_name'), 'table', ['name'], unique=True)
    op.create_table('column',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_list', sa.Boolean(), nullable=False),
    sa.Column('constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enum_id', sa.Integer(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('unique', sa.Boolean(), nullable=False),
    sa.Column('searchable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enum_id'], ['enummodel.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'name')
    )
    op.create_index(op.f('ix_column_name'), 'column', ['name'], unique=False)
    op.create_table('enumvaluemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enum_id', sa.Integer(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['enum_id'], ['enummodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enumvaluemodel_value'), 'enumvaluemodel', ['value'], unique=False)
    op.create_table('linktable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_table_id', sa.Integer(), nullable=False),
    sa.Column('to_table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_table_id'], ['table.id'], ),
    sa.ForeignKeyConstraint(['to_table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linktable_name'), 'linktable', ['name'], unique=True)
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('linkcolumn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_table_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_list', sa.Boolean(), nullable=False),
    sa.Column('constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enum_id', sa.Integer(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('unique', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['enum_id'], ['enummodel.id'], ),
    sa.ForeignKeyConstraint(['link_table_id'], ['linktable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linkrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_table_id', sa.Integer(), nullable=False),
    sa.Column('from_record_id', sa.Integer(), nullable=False),
    sa.Column('to_record_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_record_id'], ['record.id'], ),
    sa.ForeignKeyConstraint(['link_table_id'], ['linktable.id'], ),
    sa.ForeignKeyConstraint(['to_record_id'], ['record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linkrecord')
    op.drop_table('linkcolumn')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('record')
    op.drop_index(op.f('ix_linktable_name'), table_name='linktable')
    op.drop_table('linktable')
    op.drop_index(op.f('ix_enumvaluemodel_value'), table_name='enumvaluemodel')
    op.drop_table('enumvaluemodel')
    op.drop_index(op.f('ix_column_name'), table_name='column')
    op.drop_table('column')
    op.drop_index(op.f('ix_table_name'), table_name='table')
    op.drop_table('table')
    op.drop_index(op.f('ix_enummodel_name'), table_name='enummodel')
    op.drop_table('enummodel')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###

